version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/master HEAD -- docs/ .readthedocs.yaml requirements.txt;
        then
          echo "No changes to docs/ - exiting the build process."
          exit 183;
        fi
    post_install:
      - pip install -e .

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

submodules:
  include: []
  exclude: all
